package Kalkulator;
import Kalkulator.MyFrame;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class ButtonPanel extends JPanel{
	private MyButton silnia;
	private MyButton brL;
	private MyButton brR;
	public static MyButton hmm;
	private MyButton mod;
	private MyButton pow;
	private MyButton sqrt;
	private MyButton div;
	private MyButton seven;
	private MyButton eight;
	private MyButton nine;
	private MyButton multi;
	private MyButton four;
	private MyButton five;
	private MyButton six;
	private MyButton minus;
	private MyButton one;
	private MyButton two;
	private MyButton three;
	private MyButton plus;
	public static MyButton clearall;
	private MyButton zero;
	private MyButton dot;
	public static MyButton enter;
	public ButtonPanel() {
		Color liczby = new java.awt.Color(246,246,246);
		Color znaki = new java.awt.Color(207,216,238);
		Color znaki2 = new java.awt.Color(98,135,219);
		silnia = (new MyButton("Silnia","!",znaki));
		brL = (new MyButton("(","(",znaki));
		brR = (new MyButton(")",")",znaki));
		hmm = (new MyButton("← ","cof",znaki));
		mod = (new MyButton("Mod","%",znaki));
 		pow = (new MyButton("^","^",znaki));
 		sqrt = (new MyButton("√ n","#",znaki));
 		div = (new MyButton("/","/",znaki));
 		seven = (new MyButton("7","7",liczby));
 		eight = (new MyButton("8","8",liczby));
 		nine = (new MyButton("9","9",liczby));
 		multi = (new MyButton("X","*",znaki));
 		four = (new MyButton("4","4",liczby));
 		five = (new MyButton("5","5",liczby));
 		six = (new MyButton("6","6",liczby));
 		minus = (new MyButton("-","-",znaki));
 		one = (new MyButton("1","1",liczby));
 		two = (new MyButton("2","2",liczby));
 		three = (new MyButton("3","3",liczby));
 		plus = (new MyButton("+","+",znaki));
 		clearall = (new MyButton("Clear"," ",liczby));
 		zero = (new MyButton("0","0",liczby));
 		dot = (new MyButton(",",".",liczby));
 		enter = (new MyButton("Enter","=",znaki2));
		setLayout(new GridLayout(6, 4));
		add(silnia);
		add(brL);
		add(brR);
		add(hmm);
		add(mod);
		add(pow);
		add(sqrt);
		add(div);
		add(seven);
		add(eight);
		add(nine);
		add(multi);
		add(four);
		add(five);
		add(six);
		add(minus);
		add(one);
		add(two);
		add(three);
		add(plus);
		add(clearall);
		add(zero);
		add(dot);
		add(enter);
		
	}

}